version: '3'

services:

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: diltheyaislan/node:prod
    container_name: node
    networks: 
      - nodenet

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: diltheyaislan/nginx:prod
    container_name: nginx
    networks: 
      - nodenet
    ports:
      - "8080:80"
  
networks:
  nodenet:
    driver: bridge