version: '3'

services:

  node:
    build:
      context: ./node
    image: diltheyaislan/node:prod
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    networks: 
      - nodenet
    tty: true
    depends_on: 
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: diltheyaislan/nginx:prod
    container_name: nginx
    networks: 
      - nodenet
    ports:
      - "8080:80"
    depends_on: 
      - node
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - nodenet
  
networks:
  nodenet:
    driver: bridge